apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "users.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "users.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "users.fullname" . }}
      containers:
        - name: nginx
          #securityContext:
          #  capabilities:
          #    drop:
          #    - ALL
          #    add:
          #    - CAP_CHOWN
          #    - CAP_SETUID
          #  readOnlyRootFilesystem: true
          #  allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: static
              mountPath: /usr/share/nginx/html/static
              readOnly: true
            {{- range .Values.users }}
            - name: {{ .username }}
              mountPath: /usr/share/nginx/html/{{ .username }}
              readOnly: true
            {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: {{ include "users.fullname" . }}-nginx-conf
        - name: static
          secret:
            secretName: {{ include "users.fullname" . }}-static
        {{- range .Values.users }}
        - name: {{ .username }}
          secret:
            secretName: {{ .username }}
        {{- end }}