{{- range .Values.users }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users.fullname" $ }}-{{ .username}}-instructions
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "users.labels" $ | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ $.Release.Namespace }}-{{ .username }}-chain-instructions@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt"
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .username }}.{{ $.Values.ingress.host }}
      secretName: {{ include "users.fullname" $ }}-{{ .username }}-tls
  rules:
    - host: {{ .username }}.{{ $.Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ include "users.fullname" $ }}
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users.fullname" $ }}-{{ .username}}-kubeconfig
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "users.labels" $ | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ $.Release.Namespace }}-{{ .username }}-chain-kubeconfig@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt"
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .username }}.{{ $.Values.ingress.host }}
      secretName: {{ include "users.fullname" $ }}-{{ .username }}-tls
  rules:
    - host: {{ .username }}.{{ $.Values.ingress.host }}
      http:
        paths:
          - path: /kubeconfig.yaml
            pathType: Exact
            backend:
              service:
                name: {{ include "users.fullname" $ }}
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users.fullname" $ }}-{{ .username}}-token
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "users.labels" $ | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ $.Release.Namespace }}-{{ .username }}-chain-token@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt"
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .username }}.{{ $.Values.ingress.host }}
      secretName: {{ include "users.fullname" $ }}-{{ .username }}-tls
  rules:
    - host: {{ .username }}.{{ $.Values.ingress.host }}
      http:
        paths:
          - path: /token
            pathType: Exact
            backend:
              service:
                name: {{ include "users.fullname" $ }}
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users.fullname" $ }}-{{ .username}}-password
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "users.labels" $ | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ $.Release.Namespace }}-{{ .username }}-chain-password@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt"
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .username }}.{{ $.Values.ingress.host }}
      secretName: {{ include "users.fullname" $ }}-{{ .username }}-tls
  rules:
    - host: {{ .username }}.{{ $.Values.ingress.host }}
      http:
        paths:
          - path: /password
            pathType: Exact
            backend:
              service:
                name: {{ include "users.fullname" $ }}
                port:
                  name: http
{{- end }}
