apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "users.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
automountServiceAccountToken: false