apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users.fullname" . }}-static
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
type: Opaque
data:
  {{- (.Files.Glob "static/*").AsSecrets | nindent 2 }}