---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users.fullname" . }}-kubeconfigs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
type: Opaque
data: {} # fill by setup-users.sh
