# user1.campto.camp/ --> /static/instructions.html
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: rewrite-instructions
  namespace: {{ $.Release.Namespace }}
spec:
  replacePath:
    path: "/static/instructions.html"

# user1.campto.camp/favicon.ico --> /static/favicon.ico
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: rewrite-favicon
  namespace: {{ $.Release.Namespace }}
spec:
  replacePath:
    path: "/static/favicon.ico"

{{- range .Values.users }}
# Basic auth for :
# * user1.campto.camp
# * user1.campto.camp/kubeconfig
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-basicauth
  namespace: {{ $.Release.Namespace }}
spec:
  basicAuth:
    secret: {{ .username }}-basicauth
    removeHeader: true
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .username }}-basicauth
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .username }}
  password: {{ .password | quote }}

# * user1.campto.camp/kubeconfig.yaml --> /user1/kubeconfig.yaml
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-rewrite-kubeconfig
  namespace: {{ $.Release.Namespace }}
spec:
  replacePath:
    path: "/{{ .username }}/kubeconfig.yaml"

# * user1.campto.camp/token --> /user1/token
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-rewrite-token
  namespace: {{ $.Release.Namespace }}
spec:
  replacePath:
    path: "/{{ .username }}/token"

# * user1.campto.camp/password --> /user1/password
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-rewrite-password
  namespace: {{ $.Release.Namespace }}
spec:
  replacePath:
    path: "/{{ .username }}/password"

# Chain (rewrite + basicauth) Middleware for :
# * user1.campto.camp
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-chain-instructions
  namespace: {{ $.Release.Namespace }}
spec:
  chain:
    middlewares:
    - name: {{ .username }}-basicauth
    - name: rewrite-instructions
# * user1.campto.camp/kubeconfig
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-chain-kubeconfig
  namespace: {{ $.Release.Namespace }}
spec:
  chain:
    middlewares:
    - name: {{ .username }}-basicauth
    - name: {{ .username }}-rewrite-kubeconfig
# * user1.campto.camp/token
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-chain-token
  namespace: {{ $.Release.Namespace }}
spec:
  chain:
    middlewares:
    - name: {{ .username }}-basicauth
    - name: {{ .username }}-rewrite-token
# * user1.campto.camp/password
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ .username }}-chain-password
  namespace: {{ $.Release.Namespace }}
spec:
  chain:
    middlewares:
    - name: {{ .username }}-basicauth
    - name: {{ .username }}-rewrite-password
{{- end }}
