{{- range .Values.users }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .username }}
  labels:
    {{- include "users.labels" $ | nindent 4 }}
    pod-security.kubernetes.io/enforce: {{ $.Values.namespaceSecurity.podSecurityLevel }}
    pod-security.kubernetes.io/warn: {{ $.Values.namespaceSecurity.podSecurityLevel }}
  {{- with $.Values.namespace_node_selector }}
  annotations:
    "scheduler.alpha.kubernetes.io/node-selector": {{ . | quote }}
  {{- end }}
{{- end }}