{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .username }}
  namespace: {{ .username }}
  labels:
    {{- include "users.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .username }}
type: kubernetes.io/service-account-token
{{- end }}
