resource "random_password" "token" {
  count = local.variables.users

  length  = 8
  special = false
  upper   = false
  lower   = true
  numeric = false
}

locals {
  users = [for count in range(local.variables.users):
    {
      username = "user${count + 1}",
      password = random_password.token[count].result
    }
  ]
}

resource "kubernetes_namespace" "user" {
  for_each = { for u in local.users : u.username => u }

  metadata {
    annotations = {
    "scheduler.alpha.kubernetes.io/node-selector" = "k8s.scaleway.com/project-env=worker"
    }

    labels = {
      "pod-security.kubernetes.io/enforce" = "baseline"
      "pod-security.kubernetes.io/warn" = "baseline"
    }

    name = each.key
  }
}

resource "kubernetes_service_account" "user" {
  for_each = { for u in local.users : u.username => u }

  metadata {
    name = each.key
    namespace = kubernetes_namespace.user[each.key].metadata[0].name
  }
}

resource "kubernetes_token_request_v1" "user" {
  for_each = { for u in local.users : u.username => u }

  metadata {
    name      = kubernetes_service_account.user[each.key].metadata[0].name
    namespace = kubernetes_service_account.user[each.key].metadata[0].namespace
  }
  spec {
    audiences          = ["api"]
    expiration_seconds = 604800 # 7 days
  }
}




output "users_passwords" {
  value = { for u in local.users : u.username => u.password }
  sensitive = true
}

resource "kubernetes_namespace" "users" {

  metadata {
    annotations = {
    "scheduler.alpha.kubernetes.io/node-selector" = "k8s.scaleway.com/project-env=infra"
    }


    name = "users"
  }
}

resource "kubernetes_secret" "user" {
  for_each = { for u in local.users : u.username => u }

  metadata {
    name      = each.key
    namespace = kubernetes_namespace.users.metadata[0].name
  }

  data = {
    token    = kubernetes_token_request_v1.user[each.key].token
    password = each.value.password
    kubeconfig = <<-EOT
apiVersion: v1
kind: Config
clusters:
- name: ${local.variables.name}
  cluster:
    certificate-authority-data: ${var.kubeconfig.cluster_ca_certificate}
    server: ${var.kubeconfig.host}
contexts:
- name: ${each.key}@${local.variables.name}
  context:
    cluster: ${local.variables.name}
    namespace: ${each.key}
    user: ${each.key}
current-context: ${each.key}@${local.variables.name}
users:
- name: ${each.key}
  user:
    token: ${kubernetes_token_request_v1.user[each.key].token}
EOT
  }
}

resource "helm_release" "this" {
  name       = "users"
  chart      = "../../charts/users"

  namespace = kubernetes_namespace.users.metadata[0].name
  #disable_webhooks  = true
  #disable_crd_hooks = true
  #skip_crds         = true
  dependency_update  = true
  create_namespace   = false
  #timeout           = 10800
  atomic             = true
  upgrade_install    = true
  force_update       = true

  # users secrets are generated by another script so
  # pod cannot start on initial deployment
  wait = false

  values = [yamlencode({
    users = local.users
    ingress = {
      host    = local.variables.workshop_domain
      enabled = true
    }
    # Force redeployment when local chart files change
    chartChecksum = sha1(join("", [
      for f in sort(fileset("${path.module}/../../charts/users", "**")) :
      filesha1("${path.module}/../../charts/users/${f}")
    ]))
  })]

  depends_on = [ kubernetes_secret.user ]

}

resource "local_file" "users_values" {
  filename = "${path.module}/../../charts/users/values-test.yaml"
  content = yamlencode({
    users = local.users
    ingress = {
      host    = local.variables.workshop_domain
      enabled = true
    }
  })
}

#TODO: middleware rate limit for token resolution

data "http" "pagedjs" {
  url = "https://unpkg.com/pagedjs/dist/paged.polyfill.js"
}

resource "local_file" "access_cards" {
  filename = "${path.module}/../../cards/cards.html"
  content = templatefile("${path.module}/templates/cards.html.tpl", {
    users  = local.users
    domain = local.variables.workshop_domain
    css    = file("${path.module}/../../cards/styles.css")
    pagedjs = data.http.pagedjs.response_body
  })
}
