users:
  - username: user1
    password: "password1"
  - username: user2
    password: "password2"
namespace_node_selector: k8s.scaleway.com/project-env=infra

namespaceSecurity:
  # baseline: interdit les pods privilégiés
  # restricted: enforce les meilleures pratiques de sécurité
  podSecurityLevel: baseline

resourceQuota:
  enabled: true
  pods: "20"
  services: "20"
  persistentvolumeclaims: "20"
  secrets: "20"
  configmaps: "20"
  requests.cpu: "2"
  requests.memory: 1Gi
  limits.cpu: "4"
  limits.memory: 2Gi
  limitRange: # Postgres instances are using from 60Mi to 90Mi
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"


# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  host: chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
